# Generated by Django 6.0.1 on 2026-02-03 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Author')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('isbn', models.CharField(blank=True, max_length=13, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Publisher')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Pages')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['-created_at'],
            },
        ),
    ]
