# Generated by Django 6.0.1 on 2026-01-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.CharField(blank=True, help_text='artist', max_length=100, null=True, verbose_name='Artist'),
        ),
    ]
