# Generated by Django 6.0.1 on 2026-01-27 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=200, verbose_name='Title')),
                ('year', models.IntegerField(blank=True, help_text='year', null=True, verbose_name='Year')),
                ('medium', models.CharField(help_text='medium', max_length=200, verbose_name='Medium')),
                ('dimensions', models.CharField(blank=True, help_text='size', max_length=100, verbose_name='Size')),
                ('discription', models.TextField(blank=True, help_text='additional discription', verbose_name='discription')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last edited')),
                ('owner', models.ForeignKey(help_text='owner', on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ['-created_at'],
            },
        ),
    ]
