# Generated by Django 6.0.1 on 2026-01-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_artwork_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, help_text='artwork image', null=True, upload_to='artworks/%Y/%m/', verbose_name='image'),
        ),
    ]
