# Generated by Django 6.0.1 on 2026-02-04 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/%Y/%m/')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='Director')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Genre')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-created_at'],
            },
        ),
    ]
